trigger: none
pr: none

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: ReleaseName
    displayName: Insert the new release branch name
    type: string
    default: ''

variables:
  BackendBucketName: wexgateways-terraform-states-33516436317
  BackendRegion: us-east-1
  BackendDynamoDbTable: wexgateways-terraform-states-lock

stages:
  - stage: CreateRelease
    displayName: Create a new release branch from main
    jobs:
      - job: CheckoutMain
        displayName: Create release branch
        steps:
          - checkout: self
            displayName: Check out source code
            clean: true
            persistCredentials: true

          - script: |
              # Fetch the current version number
              VERSION_FILE="version.txt"
              if [ -f $VERSION_FILE ]; then
                CURRENT_VERSION=$(cat $VERSION_FILE)
              else
                echo "00.0" > $VERSION_FILE
                CURRENT_VERSION="00.0"
              fi

              # Split the current version number into major and minor parts
              IFS='.' read -r MAJOR MINOR <<< "$CURRENT_VERSION"

              # Increment the minor version
              MINOR=$((MINOR + 1))

              # Create the new version number
              NEW_VERSION="$MAJOR.$MINOR"

              # Update the version file with the new version
              echo $NEW_VERSION > $VERSION_FILE

              # Commit the updated version file back to the repository
              git config user.name "Azure DevOps"
              git config user.email "devops@azure.com"
              git add $VERSION_FILE
              git commit -m "Increment version number to $NEW_VERSION"
              git push origin main

              # Create the new release branch with the updated version number
              git checkout -b release/${{ parameters.ReleaseName }}-$NEW_VERSION && git push origin release/${{ parameters.ReleaseName }}-$NEW_VERSION
            displayName: CreateReleaseBranch
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo 'Branch release/${{ parameters.ReleaseName }}-$NEW_VERSION created!'

      - job: NotifyReleaseChannel
        displayName: Notify Release Channel
        dependsOn: CheckoutMain
        pool: server
        variables:
          gchatThreadKey: releases/$(Build.BuildId)
          DATE: $(Build.BuildId)
        steps:
          - task: InvokeRESTAPI@1
            displayName: Send notification to Google Chat
            inputs:
              connectionType: connectedServiceName
              serviceConnection: 'WEX Payment Api Release'
              urlSuffix: '&thread_key=$(gchatThreadKey)'
              method: 'POST'
              headers: '{"Content-Type":"application/json","charset":"utf-8"}'
              body: |
                {
                  "cards": [
                    {
                      "header": {
                        "title": "WEX PAYMENT API - New Release 'release/${{ parameters.ReleaseName }}-$NEW_VERSION' Branch Created.",
                        "subtitle": "$(DATE)"
                      },
                      "sections": [
                        {
                          "widgets": [
                            {
                              "keyValue": {
                                "topLabel": "🚀 NEW BRANCH: 'release/${{ parameters.ReleaseName }}-$NEW_VERSION'",
                                "content": "",
                                "contentMultiline": "true",
                                "button": {
                                  "textButton": {
                                    "text": "🔍 CHECK THE NEW BRANCH",
                                    "onClick": {
                                      "openLink": {
                                        "url": "https://dev.azure.com/WEXGateways/apps/_build/results?buildId=$(Build.BuildId)"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
